"""add column unit_price order book association

Revision ID: 09312d7cfc26
Revises: 8fae8f4bc2ae
Create Date: 2025-07-22 20:15:48.424691

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "09312d7cfc26"
down_revision: Union[str, Sequence[str], None] = "8fae8f4bc2ae"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "order_book_association",
        sa.Column("unit_price", sa.Integer(), server_default="0", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("order_book_association", "unit_price")
    # ### end Alembic commands ###
