"""add column count order book association

Revision ID: 8fae8f4bc2ae
Revises: dc1d93375756
Create Date: 2025-07-22 18:34:07.918658

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8fae8f4bc2ae"
down_revision: Union[str, Sequence[str], None] = "dc1d93375756"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "order_book_association",
        sa.Column("count", sa.Integer(), server_default="1", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("order_book_association", "count")
    # ### end Alembic commands ###
